//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.17 at 04:35:02 PM CET 
//

package us.es.idea.pnml;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="net">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="place" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="graphics">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="position">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                               &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="dimension">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                               &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="transition" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="graphics">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="position">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                               &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="dimension">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                               &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="fill">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="arc" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="arctype">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "net" })
@XmlRootElement(name = "pnml")
public class Pnml implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 3311612141906036550L;
	@XmlElement(required = true)
	protected Pnml.Net net;

	/**
	 * Gets the value of the net property.
	 * 
	 * @return possible object is {@link Pnml.Net }
	 * 
	 */
	public Pnml.Net getNet() {
		return net;
	}

	/**
	 * Sets the value of the net property.
	 * 
	 * @param value
	 *            allowed object is {@link Pnml.Net }
	 * 
	 */
	public void setNet(Pnml.Net value) {
		this.net = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="name">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="place" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="name">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="graphics">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="position">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
	 *                                     &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                             &lt;element name="dimension">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
	 *                                     &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="transition" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="name">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="graphics">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="position">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
	 *                                     &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                             &lt;element name="dimension">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
	 *                                     &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                             &lt;element name="fill">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="arc" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="name">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="arctype">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "name", "place", "transition", "arc" })
	public static class Net implements Serializable{

		/**
		 * 
		 */
		private static final long serialVersionUID = -9149164771036699397L;
		@XmlElement(required = true)
		protected Pnml.Net.Name name;
		@XmlElement(required = true)
		protected List<Pnml.Net.Place> place;
		@XmlElement(required = true)
		protected List<Pnml.Net.Transition> transition;
		@XmlElement(required = true)
		protected List<Pnml.Net.Arc> arc;
		@XmlAttribute(name = "id")
		protected String id;
		@XmlAttribute(name = "type")
		protected String type;

		/**
		 * Gets the value of the name property.
		 * 
		 * @return possible object is {@link Pnml.Net.Name }
		 * 
		 */
		public Pnml.Net.Name getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *            allowed object is {@link Pnml.Net.Name }
		 * 
		 */
		public void setName(Pnml.Net.Name value) {
			this.name = value;
		}

		/**
		 * Gets the value of the place property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the place property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPlace().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Pnml.Net.Place }
		 * 
		 * 
		 */
		public List<Pnml.Net.Place> getPlace() {
			if (place == null) {
				place = new ArrayList<Pnml.Net.Place>();
			}
			return this.place;
		}

		/**
		 * Gets the value of the transition property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the transition property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getTransition().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Pnml.Net.Transition }
		 * 
		 * 
		 */
		public List<Pnml.Net.Transition> getTransition() {
			if (transition == null) {
				transition = new ArrayList<Pnml.Net.Transition>();
			}
			return this.transition;
		}

		/**
		 * Gets the value of the arc property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the arc property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getArc().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Pnml.Net.Arc }
		 * 
		 * 
		 */
		public List<Pnml.Net.Arc> getArc() {
			if (arc == null) {
				arc = new ArrayList<Pnml.Net.Arc>();
			}
			return this.arc;
		}

		/**
		 * Gets the value of the id property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getId() {
			return id;
		}

		/**
		 * Sets the value of the id property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setId(String value) {
			this.id = value;
		}

		/**
		 * Gets the value of the type property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getType() {
			return type;
		}

		/**
		 * Sets the value of the type property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setType(String value) {
			this.type = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="name">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="arctype">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "name", "arctype" })
		public static class Arc implements Serializable{

			/**
			 * 
			 */
			private static final long serialVersionUID = -43159398881691362L;
			@XmlElement(required = true)
			protected Pnml.Net.Arc.Name name;
			@XmlElement(required = true)
			protected Pnml.Net.Arc.Arctype arctype;
			@XmlAttribute(name = "id")
			protected String id;
			@XmlAttribute(name = "source")
			protected String source;
			@XmlAttribute(name = "target")
			protected String target;

			/**
			 * Gets the value of the name property.
			 * 
			 * @return possible object is {@link Pnml.Net.Arc.Name }
			 * 
			 */
			public Pnml.Net.Arc.Name getName() {
				return name;
			}

			/**
			 * Sets the value of the name property.
			 * 
			 * @param value
			 *            allowed object is {@link Pnml.Net.Arc.Name }
			 * 
			 */
			public void setName(Pnml.Net.Arc.Name value) {
				this.name = value;
			}

			/**
			 * Gets the value of the arctype property.
			 * 
			 * @return possible object is {@link Pnml.Net.Arc.Arctype }
			 * 
			 */
			public Pnml.Net.Arc.Arctype getArctype() {
				return arctype;
			}

			/**
			 * Sets the value of the arctype property.
			 * 
			 * @param value
			 *            allowed object is {@link Pnml.Net.Arc.Arctype }
			 * 
			 */
			public void setArctype(Pnml.Net.Arc.Arctype value) {
				this.arctype = value;
			}

			/**
			 * Gets the value of the id property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getId() {
				return id;
			}

			/**
			 * Sets the value of the id property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setId(String value) {
				this.id = value;
			}

			/**
			 * Gets the value of the source property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSource() {
				return source;
			}

			/**
			 * Sets the value of the source property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSource(String value) {
				this.source = value;
			}

			/**
			 * Gets the value of the target property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getTarget() {
				return target;
			}

			/**
			 * Sets the value of the target property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setTarget(String value) {
				this.target = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "text" })
			public static class Arctype implements Serializable{

				/**
				 * 
				 */
				private static final long serialVersionUID = -2337818399469343810L;
				@XmlElement(required = true)
				protected String text;

				/**
				 * Gets the value of the text property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getText() {
					return text;
				}

				/**
				 * Sets the value of the text property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setText(String value) {
					this.text = value;
				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "text" })
			public static class Name implements Serializable{

				/**
				 * 
				 */
				private static final long serialVersionUID = 7302338020070449706L;
				protected int text;

				/**
				 * Gets the value of the text property.
				 * 
				 */
				public int getText() {
					return text;
				}

				/**
				 * Sets the value of the text property.
				 * 
				 */
				public void setText(int value) {
					this.text = value;
				}

			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "text" })
		public static class Name implements Serializable{

			/**
			 * 
			 */
			private static final long serialVersionUID = 1261032514838836912L;
			@XmlElement(required = true)
			protected String text;

			/**
			 * Gets the value of the text property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getText() {
				return text;
			}

			/**
			 * Sets the value of the text property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setText(String value) {
				this.text = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="name">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="graphics">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="position">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
		 *                           &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                   &lt;element name="dimension">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
		 *                           &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "name", "graphics" })
		public static class Place implements Serializable{

			/**
			 * 
			 */
			private static final long serialVersionUID = 8376658190916502474L;
			@XmlElement(required = true)
			protected Pnml.Net.Place.Name name;
			@XmlElement(required = true)
			protected Pnml.Net.Place.Graphics graphics;
			@XmlAttribute(name = "id")
			protected String id;

			/**
			 * Gets the value of the name property.
			 * 
			 * @return possible object is {@link Pnml.Net.Place.Name }
			 * 
			 */
			public Pnml.Net.Place.Name getName() {
				return name;
			}

			/**
			 * Sets the value of the name property.
			 * 
			 * @param value
			 *            allowed object is {@link Pnml.Net.Place.Name }
			 * 
			 */
			public void setName(Pnml.Net.Place.Name value) {
				this.name = value;
			}

			/**
			 * Gets the value of the graphics property.
			 * 
			 * @return possible object is {@link Pnml.Net.Place.Graphics }
			 * 
			 */
			public Pnml.Net.Place.Graphics getGraphics() {
				return graphics;
			}

			/**
			 * Sets the value of the graphics property.
			 * 
			 * @param value
			 *            allowed object is {@link Pnml.Net.Place.Graphics }
			 * 
			 */
			public void setGraphics(Pnml.Net.Place.Graphics value) {
				this.graphics = value;
			}

			/**
			 * Gets the value of the id property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getId() {
				return id;
			}

			/**
			 * Sets the value of the id property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setId(String value) {
				this.id = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="position">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
			 *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *         &lt;element name="dimension">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
			 *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "position", "dimension" })
			public static class Graphics implements Serializable{

				/**
				 * 
				 */
				private static final long serialVersionUID = 6935182909312083562L;
				@XmlElement(required = true)
				protected Pnml.Net.Place.Graphics.Position position;
				@XmlElement(required = true)
				protected Pnml.Net.Place.Graphics.Dimension dimension;

				/**
				 * Gets the value of the position property.
				 * 
				 * @return possible object is
				 *         {@link Pnml.Net.Place.Graphics.Position }
				 * 
				 */
				public Pnml.Net.Place.Graphics.Position getPosition() {
					return position;
				}

				/**
				 * Sets the value of the position property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link Pnml.Net.Place.Graphics.Position }
				 * 
				 */
				public void setPosition(Pnml.Net.Place.Graphics.Position value) {
					this.position = value;
				}

				/**
				 * Gets the value of the dimension property.
				 * 
				 * @return possible object is
				 *         {@link Pnml.Net.Place.Graphics.Dimension }
				 * 
				 */
				public Pnml.Net.Place.Graphics.Dimension getDimension() {
					return dimension;
				}

				/**
				 * Sets the value of the dimension property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link Pnml.Net.Place.Graphics.Dimension }
				 * 
				 */
				public void setDimension(Pnml.Net.Place.Graphics.Dimension value) {
					this.dimension = value;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
				 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "")
				public static class Dimension implements Serializable{

					/**
					 * 
					 */
					private static final long serialVersionUID = 3947394277197785680L;
					@XmlAttribute(name = "x")
					protected BigDecimal x;
					@XmlAttribute(name = "y")
					protected BigDecimal y;

					/**
					 * Gets the value of the x property.
					 * 
					 * @return possible object is {@link BigDecimal }
					 * 
					 */
					public BigDecimal getX() {
						return x;
					}

					/**
					 * Sets the value of the x property.
					 * 
					 * @param value
					 *            allowed object is {@link BigDecimal }
					 * 
					 */
					public void setX(BigDecimal value) {
						this.x = value;
					}

					/**
					 * Gets the value of the y property.
					 * 
					 * @return possible object is {@link BigDecimal }
					 * 
					 */
					public BigDecimal getY() {
						return y;
					}

					/**
					 * Sets the value of the y property.
					 * 
					 * @param value
					 *            allowed object is {@link BigDecimal }
					 * 
					 */
					public void setY(BigDecimal value) {
						this.y = value;
					}

				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
				 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "")
				public static class Position implements Serializable{

					/**
					 * 
					 */
					private static final long serialVersionUID = 7156167533084228490L;
					@XmlAttribute(name = "x")
					protected BigDecimal x;
					@XmlAttribute(name = "y")
					protected BigDecimal y;

					/**
					 * Gets the value of the x property.
					 * 
					 * @return possible object is {@link BigDecimal }
					 * 
					 */
					public BigDecimal getX() {
						return x;
					}

					/**
					 * Sets the value of the x property.
					 * 
					 * @param value
					 *            allowed object is {@link BigDecimal }
					 * 
					 */
					public void setX(BigDecimal value) {
						this.x = value;
					}

					/**
					 * Gets the value of the y property.
					 * 
					 * @return possible object is {@link BigDecimal }
					 * 
					 */
					public BigDecimal getY() {
						return y;
					}

					/**
					 * Sets the value of the y property.
					 * 
					 * @param value
					 *            allowed object is {@link BigDecimal }
					 * 
					 */
					public void setY(BigDecimal value) {
						this.y = value;
					}

				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "text" })
			public static class Name implements Serializable{

				/**
				 * 
				 */
				private static final long serialVersionUID = -6292097780992809406L;
				@XmlElement(required = true)
				protected String text;

				/**
				 * Gets the value of the text property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getText() {
					return text;
				}

				/**
				 * Sets the value of the text property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setText(String value) {
					this.text = value;
				}

			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="name">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="graphics">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="position">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
		 *                           &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                   &lt;element name="dimension">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
		 *                           &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                   &lt;element name="fill">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "name", "graphics" })
		public static class Transition implements Serializable{

			/**
			 * 
			 */
			private static final long serialVersionUID = 5175176229588647856L;
			@XmlElement(required = true)
			protected Pnml.Net.Transition.Name name;
			@XmlElement(required = true)
			protected Pnml.Net.Transition.Graphics graphics;
			@XmlAttribute(name = "id")
			protected String id;

			/**
			 * Gets the value of the name property.
			 * 
			 * @return possible object is {@link Pnml.Net.Transition.Name }
			 * 
			 */
			public Pnml.Net.Transition.Name getName() {
				return name;
			}

			/**
			 * Sets the value of the name property.
			 * 
			 * @param value
			 *            allowed object is {@link Pnml.Net.Transition.Name }
			 * 
			 */
			public void setName(Pnml.Net.Transition.Name value) {
				this.name = value;
			}

			/**
			 * Gets the value of the graphics property.
			 * 
			 * @return possible object is {@link Pnml.Net.Transition.Graphics }
			 * 
			 */
			public Pnml.Net.Transition.Graphics getGraphics() {
				return graphics;
			}

			/**
			 * Sets the value of the graphics property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link Pnml.Net.Transition.Graphics }
			 * 
			 */
			public void setGraphics(Pnml.Net.Transition.Graphics value) {
				this.graphics = value;
			}

			/**
			 * Gets the value of the id property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getId() {
				return id;
			}

			/**
			 * Sets the value of the id property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setId(String value) {
				this.id = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="position">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
			 *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *         &lt;element name="dimension">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
			 *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *         &lt;element name="fill">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "position", "dimension", "fill" })
			public static class Graphics implements Serializable{

				/**
				 * 
				 */
				private static final long serialVersionUID = -7964225657392476629L;
				@XmlElement(required = true)
				protected Pnml.Net.Transition.Graphics.Position position;
				@XmlElement(required = true)
				protected Pnml.Net.Transition.Graphics.Dimension dimension;
				@XmlElement(required = true)
				protected Pnml.Net.Transition.Graphics.Fill fill;

				/**
				 * Gets the value of the position property.
				 * 
				 * @return possible object is
				 *         {@link Pnml.Net.Transition.Graphics.Position }
				 * 
				 */
				public Pnml.Net.Transition.Graphics.Position getPosition() {
					return position;
				}

				/**
				 * Sets the value of the position property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link Pnml.Net.Transition.Graphics.Position }
				 * 
				 */
				public void setPosition(Pnml.Net.Transition.Graphics.Position value) {
					this.position = value;
				}

				/**
				 * Gets the value of the dimension property.
				 * 
				 * @return possible object is
				 *         {@link Pnml.Net.Transition.Graphics.Dimension }
				 * 
				 */
				public Pnml.Net.Transition.Graphics.Dimension getDimension() {
					return dimension;
				}

				/**
				 * Sets the value of the dimension property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link Pnml.Net.Transition.Graphics.Dimension }
				 * 
				 */
				public void setDimension(Pnml.Net.Transition.Graphics.Dimension value) {
					this.dimension = value;
				}

				/**
				 * Gets the value of the fill property.
				 * 
				 * @return possible object is
				 *         {@link Pnml.Net.Transition.Graphics.Fill }
				 * 
				 */
				public Pnml.Net.Transition.Graphics.Fill getFill() {
					return fill;
				}

				/**
				 * Sets the value of the fill property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link Pnml.Net.Transition.Graphics.Fill }
				 * 
				 */
				public void setFill(Pnml.Net.Transition.Graphics.Fill value) {
					this.fill = value;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
				 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "")
				public static class Dimension implements Serializable{

					/**
					 * 
					 */
					private static final long serialVersionUID = 8837835211153449509L;
					@XmlAttribute(name = "x")
					protected BigDecimal x;
					@XmlAttribute(name = "y")
					protected BigDecimal y;

					/**
					 * Gets the value of the x property.
					 * 
					 * @return possible object is {@link BigDecimal }
					 * 
					 */
					public BigDecimal getX() {
						return x;
					}

					/**
					 * Sets the value of the x property.
					 * 
					 * @param value
					 *            allowed object is {@link BigDecimal }
					 * 
					 */
					public void setX(BigDecimal value) {
						this.x = value;
					}

					/**
					 * Gets the value of the y property.
					 * 
					 * @return possible object is {@link BigDecimal }
					 * 
					 */
					public BigDecimal getY() {
						return y;
					}

					/**
					 * Sets the value of the y property.
					 * 
					 * @param value
					 *            allowed object is {@link BigDecimal }
					 * 
					 */
					public void setY(BigDecimal value) {
						this.y = value;
					}

				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" />
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "")
				public static class Fill implements Serializable{

					/**
					 * 
					 */
					private static final long serialVersionUID = -5582463139788922187L;
					@XmlAttribute(name = "color")
					protected String color;

					/**
					 * Gets the value of the color property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getColor() {
						return color;
					}

					/**
					 * Sets the value of the color property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setColor(String value) {
						this.color = value;
					}

				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}decimal" />
				 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}decimal" />
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "")
				public static class Position implements Serializable{

					/**
					 * 
					 */
					private static final long serialVersionUID = -3671787182529010078L;
					@XmlAttribute(name = "x")
					protected BigDecimal x;
					@XmlAttribute(name = "y")
					protected BigDecimal y;

					/**
					 * Gets the value of the x property.
					 * 
					 * @return possible object is {@link BigDecimal }
					 * 
					 */
					public BigDecimal getX() {
						return x;
					}

					/**
					 * Sets the value of the x property.
					 * 
					 * @param value
					 *            allowed object is {@link BigDecimal }
					 * 
					 */
					public void setX(BigDecimal value) {
						this.x = value;
					}

					/**
					 * Gets the value of the y property.
					 * 
					 * @return possible object is {@link BigDecimal }
					 * 
					 */
					public BigDecimal getY() {
						return y;
					}

					/**
					 * Sets the value of the y property.
					 * 
					 * @param value
					 *            allowed object is {@link BigDecimal }
					 * 
					 */
					public void setY(BigDecimal value) {
						this.y = value;
					}

				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "text" })
			public static class Name implements Serializable{

				/**
				 * 
				 */
				private static final long serialVersionUID = 3302438214692838200L;
				@XmlElement(required = true)
				protected String text;

				/**
				 * Gets the value of the text property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getText() {
					return text;
				}

				/**
				 * Sets the value of the text property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setText(String value) {
					this.text = value;
				}

			}

		}

	}

}
